### ISSUE TITLE
(Kenneth - Sprint 1)Producer image bring up for Raspberry Pi

### ISSUE THREAD

**Issue by emma-harper** [cu-ecen-aeld/final-project-emma-harper#1]
DoD:
- [x] Create an image for the raspberry pi using buildroot image for the producer.
- [x] Image created boots without issue.
- [x] HDMI output, keyboard/mouse, and SSH work in the current image.
- [x] I2C device is loaded in the /dev folder
- [x] Able to detect I2C device using i2cdetect
- [x] Startup script to automatically load i2c device on boot
- [x]  (Optional) Get WIFI working so that ethernet cable is not required.

Blockers:
No blockers at the time

**Comment by kejo1166** [comment]
I successfully created raspberry pi image that boots on 3B and 3B+. 

![IMG_0589](https://user-images.githubusercontent.com/86031233/160951861-cdbd2a52-f0c5-4309-a22f-97b4e15fe04e.jpg)

I2C automatically loads i2c-1

![Screen Shot 2022-03-30 19 24 53](https://user-images.githubusercontent.com/86031233/160952259-b0689190-f90a-403a-a3d6-31c1d6d610d5.png)

![Screen Shot 2022-03-30 19 25 48](https://user-images.githubusercontent.com/86031233/160952192-f43b0ac7-eaf8-4d86-adc4-a8b05da7c3ef.png)

Both ethernet and wifi are working.  Wifi connects automatically with preconfigured SSID and password.

![Screen Shot 2022-03-30 19 24 06](https://user-images.githubusercontent.com/86031233/160952041-e25fa9ec-a260-4e0c-96fd-9a367ccda447.png)

Python successfully added.
![Screen Shot 2022-03-30 19 27 19](https://user-images.githubusercontent.com/86031233/160952376-bd2670f1-90ba-4eb6-8a86-ef5c79820a59.png)
