### ISSUE TITLE
(Emma - Sprint 1) Establish SPI driver within raspberry pi image

### ISSUE THREAD

**Issue by kejo1166** [cu-ecen-aeld/final-project-emma-harper#5]
DoD:

- [x] Verify able to communicate with SPI device using SPI module

Blockers:
Not at the time.

**Comment by emma-harper** [comment]
completed with ability to load spi module and open spi dev with python script on raspberry pi
![image](https://user-images.githubusercontent.com/45604867/161461866-391feb37-f69f-4758-89bb-643488b096aa.jpeg)
