### ISSUE TITLE
(Emma - Sprint 2) Develop SPI communication with LED display

### ISSUE THREAD

**Issue by kejo1166** [cu-ecen-aeld/final-project-emma-harper#6]

**Comment by emma-harper** [comment]
completed LED display interface with sense hat. Am able to post scrolling message with dummy data - pulled from rabbitMQ server - for pressure, accel, gyroscope, and magnetometer.
![image](https://user-images.githubusercontent.com/45604867/161854911-1cebacb8-f8c1-4bf8-b05e-5990398412bd.jpeg)

![image](https://user-images.githubusercontent.com/45604867/161854962-03790b97-80cc-4563-a185-0a2d5f1444e3.jpeg)
